export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST" 
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS" 
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE" 

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST" 
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS" 
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE" 

